name: ne_chu_show
description: "flutter application for ne chu show"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  build_runner: ^2.4.12
  riverpod_lint: ^2.3.12
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.2
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.10+1
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding_guideline_sample_nt_rd_lg.svg
  
